services:
  - name: express-app
    type: web
    buildCommand: |
      yarn install
      yarn run build
    startCommand: node server.js
    healthCheckPath: /
    skipCleanup: true
    env:
      NODE_VERSION: 14.20.1
